"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";
import type { User, Channel, ChatMessage, Reminder } from "./types";

interface AppState {
  // User state
  user: User | null;
  setUser: (user: User | null) => void;

  // Channels
  channels: Channel[];
  setChannels: (channels: Channel[]) => void;
  selectedChannel: Channel | null;
  setSelectedChannel: (channel: Channel | null) => void;
  updateChannelUnread: (channelId: string, count: number) => void;

  // Chat messages per channel
  chatMessagesByChannel: Record<string, ChatMessage[]>;
  addChatMessage: (channelId: string, message: ChatMessage) => void;
  getChatMessages: (channelId: string) => ChatMessage[];
  clearChannelChat: (channelId: string) => void;

  // Reminders (auto-generated by agent)
  reminders: Reminder[];
  addReminder: (reminder: Reminder) => void;
  markReminderRead: (id: string) => void;
  markReminderComplete: (id: string) => void;
  deleteReminder: (id: string) => void;
  unreadRemindersCount: () => number;

  // UI State
  isLoading: boolean;
  setIsLoading: (loading: boolean) => void;
  showNotifications: boolean;
  setShowNotifications: (show: boolean) => void;
}

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      // User state
      user: null,
      setUser: (user) => set({ user }),

      // Channels
      channels: [],
      setChannels: (channels) => set({ channels }),
      selectedChannel: null,
      setSelectedChannel: (selectedChannel) => set({ selectedChannel }),
      updateChannelUnread: (channelId, count) =>
        set((state) => ({
          channels: state.channels.map((c) =>
            c.id === channelId ? { ...c, unreadCount: count } : c
          ),
        })),

      // Chat messages per channel
      chatMessagesByChannel: {},
      addChatMessage: (channelId, message) =>
        set((state) => ({
          chatMessagesByChannel: {
            ...state.chatMessagesByChannel,
            [channelId]: [
              ...(state.chatMessagesByChannel[channelId] || []),
              message,
            ],
          },
        })),
      getChatMessages: (channelId) => {
        return get().chatMessagesByChannel[channelId] || [];
      },
      clearChannelChat: (channelId) =>
        set((state) => ({
          chatMessagesByChannel: {
            ...state.chatMessagesByChannel,
            [channelId]: [],
          },
        })),

      // Reminders
      reminders: [],
      addReminder: (reminder) =>
        set((state) => ({ reminders: [reminder, ...state.reminders] })),
      markReminderRead: (id) =>
        set((state) => ({
          reminders: state.reminders.map((r) =>
            r.id === id ? { ...r, isRead: true } : r
          ),
        })),
      markReminderComplete: (id) =>
        set((state) => ({
          reminders: state.reminders.map((r) =>
            r.id === id ? { ...r, isCompleted: true } : r
          ),
        })),
      deleteReminder: (id) =>
        set((state) => ({
          reminders: state.reminders.filter((r) => r.id !== id),
        })),
      unreadRemindersCount: () => {
        return get().reminders.filter((r) => !r.isRead && !r.isCompleted).length;
      },

      // UI State
      isLoading: false,
      setIsLoading: (isLoading) => set({ isLoading }),
      showNotifications: false,
      setShowNotifications: (showNotifications) => set({ showNotifications }),
    }),
    {
      name: "slacksum-storage",
      partialize: (state) => ({
        user: state.user,
        reminders: state.reminders,
      }),
    }
  )
);
